version: "3"

services:
  db:
    restart: always
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql/database/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=c1Zl6tC93AuTfKC

  storage:
    restart: always
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"

  user-service:
    restart: always
    image: asbind/ecomuser:v6
    container_name: user-container
    ports:
      - "5001:5000"
    depends_on:
      - "db"
      - "storage"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - BUCKET_NAME=ecommerce
      - AWS_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - STORAGE_PROVIDER=minio
      - STORAGE_HOST=storage
      - STORAGE_PORT=9000
      - STORAGE_HOST_EXT=localhost
      - STORAGE_PORT_EXT=9000
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:c1Zl6tC93AuTfKC@db:3306/userdb

  product-service:
    restart: always
    image: asbind/ecomproduct:v6
    container_name: product-container
    ports:
      - "5002:5000"
    depends_on:
      - "db"
      - "storage"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - BUCKET_NAME=ecommerce
      - AWS_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - STORAGE_PROVIDER=minio
      - STORAGE_HOST=storage
      - STORAGE_PORT=9000
      - STORAGE_HOST_EXT=localhost
      - STORAGE_PORT_EXT=9000
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:c1Zl6tC93AuTfKC@db:3306/productdb

  order-service:
    restart: always
    image: asbind/ecomorder:v6
    container_name: order-container
    ports:
      - "5003:5000"
    depends_on:
      - "db"
      - "user-service"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:c1Zl6tC93AuTfKC@db:3306/orderdb
      - USER_SERVICE_URL=http://user-service:5000
      
  review-service:
    restart: always
    image: asbind/ecomreview:v6
    container_name: review-container
    ports:
      - "5004:5000"
    depends_on:
      - "db"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:c1Zl6tC93AuTfKC@db:3306/reviewdb

  frontend-service:
    restart: always
    image: asbind/ecomfrontend:v6
    container_name: frontend-container
    ports:
      - "5000:5000"
    depends_on:
      - "user-service"
      - "product-service"
      - "order-service"
      - "review-service"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - WTF_CSRF_SECRET_KEY=sEWQkE9oYBiF5fVJnm278i7
      - USER_SERVICE_URL=http://user-service:5000
      - PRODUCT_SERVICE_URL=http://product-service:5000
      - ORDER_SERVICE_URL=http://order-service:5000
      - REVIEW_SERVICE_URL=http://review-service:5000
