version: "3"

services:
  user-service:
    restart: always
    image: asbind/ecomuser:v6
    container_name: user-container
    ports:
      - "5001:5000"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - BUCKET_NAME=microservices-ecommerce-app
      - CLOUDFRONT_URL=https://dn2aztcn1xe1u.cloudfront.net
      - AWS_ACCESS_KEY=AKIATHISISANEXAMPLEKEY
      - AWS_SECRET_KEY=APthisisanexamplesecretkey
      - STORAGE_PROVIDER=s3
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://admin:S9c1Zl6tC93AuTfKCLLV@database-1.czqnyxmkvtxg.us-west-2.rds.amazonaws.com:3306/user

  product-service:
    restart: always
    image: asbind/ecomproduct:v6
    container_name: product-container
    ports:
      - "5002:5000"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - BUCKET_NAME=microservices-ecommerce-app
      - CLOUDFRONT_URL=https://dn2aztcn1xe1u.cloudfront.net
      - AWS_ACCESS_KEY=AKIATHISISANEXAMPLEKEY
      - AWS_SECRET_KEY=APthisisanexamplesecretkey
      - STORAGE_PROVIDER=s3
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://admin:S9c1Zl6tC93AuTfKCLLV@database-1.czqnyxmkvtxg.us-west-2.rds.amazonaws.com:3306/product

  order-service:
    restart: always
    image: asbind/ecomorder:v6
    container_name: order-container
    ports:
      - "5003:5000"
    depends_on:
      - "user-service"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://admin:S9c1Zl6tC93AuTfKCLLV@database-1.czqnyxmkvtxg.us-west-2.rds.amazonaws.com:3306/orderdb
      - USER_SERVICE_URL=http://user-service:5000
      
  review-service:
    restart: always
    image: asbind/ecomreview:v6
    container_name: review-container
    ports:
      - "5004:5000"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://admin:S9c1Zl6tC93AuTfKCLLV@database-1.czqnyxmkvtxg.us-west-2.rds.amazonaws.com:3306/review

  frontend-service:
    restart: always
    image: asbind/ecomfrontend:v6
    container_name: frontend-container
    ports:
      - "5000:5000"
    depends_on:
      - "user-service"
      - "product-service"
      - "order-service"
      - "review-service"
    environment:
      - SECRET_KEY=DoWgTDq87Kmne3TsCjNFabP
      - WTF_CSRF_SECRET_KEY=sEWQkE9oYBiF5fVJnm278i7
      - USER_SERVICE_URL=http://user-service:5000
      - PRODUCT_SERVICE_URL=http://product-service:5000
      - ORDER_SERVICE_URL=http://order-service:5000
      - REVIEW_SERVICE_URL=http://review-service:5000
